### ISSUE TITLE
Link anchors

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink.github.io#1] opened 2017-01-03 02:56 UTC
Is there a reason for this change? It looks like the intention was to use the shorthand anchor names.
https://github.com/streamlink/streamlink.github.io/commit/3778921815429463d15616113d9fe8c5bc097785
This was automatically committed by the pushdocs.sh script...

This breaks links linking to specific double-dash commands (eg. `--hls-live-edge`)
Old:
https://streamlink.github.io/cli.html#cmdoption--hls-live-edge
New:
https://streamlink.github.io/cli.html#cmdoption-hls-live-edge

**Comment by sbstp** [comment] 2017-01-03 03:01
I'm not sure how this happened, it might be that the sphinx version changed.

**Comment by bastimeyer** [comment] 2017-01-26 18:04
This there a fix for that? The Twitch GUI and its wiki are linking to these parameters in the documentation and it's a bit inconsistent having some parameters that have anchors with two leading dashes and some others that don't.

**Comment by bastimeyer** [comment] 2017-03-16 21:19
@beardypig 
Could you please take a look at this whenever you have the time? I'm a bit lost in the sphinx documentation. Thanks!

**Comment by beardypig** [comment] 2017-03-16 22:06
Yep, I'll take a look :-)

**Comment by beardypig** [comment] 2017-03-17 15:03
It was caused by Sphinx `1.5+`. With `1.4.9` the old style `--` anchors are generated. I'll see if we can support both, cos we've had `--` for quite a while so I'm sure there are those links around in issues, PRs, etc.

**Comment by gravyboat** [comment] 2017-03-17 16:25
I'm okay with just moving to the 1.5.3 style. It will definitely break some links but I would rather not have the confusion it possibly creates.

**Comment by gravyboat** [comment] 2017-05-22 16:28
Closing since https://github.com/streamlink/streamlink/pull/940 is merged.

**Closed by gravyboat** 2017-05-22 16:28 UTC
